### ISSUE TITLE
Could not install or upgarde get frozen class

### ISSUE THREAD

**Issue by frap** [d12frosted/homebrew-emacs-plus#602]
Please make sure to follow these steps (and mark the checkboxes):

- [ x ] run `brew update` and try to reproduce the issue again
- [ x ] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ x ] run `brew config` and `brew doctor` and include their output

## What you were trying to do
just upgrade emacs-plus@29 to emacs-plus@29.1 then tryed to upgrade to emacs-plus@30 same error

## What happened (include command output)

<pre>
 brew install emacs-plus@30                                        
Error: can't modify frozen class

 …/kapua-networking-platform →🌱 fix/spf-rec⋮ 🏎💨 v1.5.5default on 🅰 production/PowerUser (Syd) [X] 
✖ brew install emacs-plus@30 --with-native-comp --with-retro-gnu-meditate-levitate-icon
Error: can't modify frozen class
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.1.5-28-g385cf78
ORIGIN: https://github.com/Homebrew/brew
HEAD: 385cf78efac85321f8c1074472a0ffa494751f57
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72286a09e6644cff2b342b43d1e2c3c3e7bbe603
Core tap last commit: 2 days ago
Core tap branch: master
Core tap JSON: 15 Aug 20:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_BAT_THEME: Dracula
HOMEBREW_CASK_OPTS: []
HOMEBREW_DEVELOPER: set
HOMEBREW_EDITOR: emacc
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h
</pre>

**Comment by frap** [comment]
fixed up brew doctor and upgarded brew still same error
<pre>
brew doctor              
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

 ~/.local/bin tomó 4s 
🕙[ 09:04:05 ] ✖ brew install emacs-plus@30 --with-retro-gnu-meditate-levitate-icon
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################## 100.0%
Error: can't modify frozen class
</pre>

**Comment by frap** [comment]
fixed removed these ENV variables in my .zshrc
<pre>
export PATH="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin:$PATH"
export HOMEBREW_AUTO_UPDATE_SECS=3600
export HOMEBREW_DEVELOPER=1
export HOMEBREW_GIT_FILTER_TREE_ZERO=1
</pre>

**Comment by d12frosted** [comment]
Oh wow. That's interesting. Wonder if it has something to do with `HOMEBREW_DEVELOPER` or `HOMEBREW_GIT_FILTER_TREE_ZERO`. Path should not affect anything.

**Comment by d12frosted** [comment]
Ok, checked myself. Setting `HOMEBREW_DEVELOPER` to `1` breaks installation. Not sure why though. Not that familiar with brew internals or ruby in general 😓

**Comment by cilia** [comment]
I'm having the same error when installing 29.1 (delete and reinstall, to be precise) and my `brew config` looks like this:

```
HOMEBREW_VERSION: 4.1.7-43-ge7d0625
ORIGIN: https://github.com/Homebrew/brew
HEAD: e7d0625776dca58c81b03c19eeda1af8bd6bb58e
Last commit: 13 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 115de939f93ff95e858a759eec59da456fe89343
Core tap last commit: 7 months ago
Core tap branch: master
Core tap JSON: 03 Sep 11:07 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 11.7.9-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false
```

 `brew doctor` shows no obvious related problem:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
```

And I don't have `HOMEBREW_DEVELOPER` or `HOMEBREW_GIT_FILTER_TREE_ZERO` set in my `bash_profile`, so what gives?

**Comment by cilia** [comment]
I've also tried untapping and tapping the repository, still the same error.

**Comment by cilia** [comment]
This is the `--debug` info:

```
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@29.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading make from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading autoconf from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gnu-sed from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gnu-tar from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading grep from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading awk from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading coreutils from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading pkg-config from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading texinfo from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading xz from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gnutls from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading librsvg from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading little-cms2 from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading jansson from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading tree-sitter from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading imagemagick from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading dbus from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading mailutils from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libgccjit from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gcc from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gmp from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::AliasAPILoader): loading jpeg from API
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zlib from API
Error: can't modify frozen class
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/class_utils.rb:84:in `define_method'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/class_utils.rb:84:in `block in def_with_visibility'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/class_utils.rb:73:in `module_exec'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/class_utils.rb:73:in `def_with_visibility'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:88:in `create_validator_slow'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:80:in `block (2 levels) in create_validator_method'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/decl_state.rb:25:in `without_on_method_added'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:70:in `block in create_validator_method'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:533:in `without_ruby_warnings'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:69:in `create_validator_method'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:38:in `wrap_method_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:402:in `unwrap_method'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:320:in `_handle_missing_method_signature'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:252:in `block in _on_method_added'
/opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@29.rb:102:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:484:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:484:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:761:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:126:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:204:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install.rb:195:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by aamikkelsenWH** [comment]
Tried to same as above - get the same error and debug trace as @cilia

**Comment by d12frosted** [comment]
Great summary here: https://github.com/d12frosted/homebrew-emacs-plus/issues/608

**Comment by d12frosted** [comment]
The breakage was caused by change in homebrew - https://github.com/Homebrew/brew/commit/e7d0625776dca58c81b03c19eeda1af8bd6bb58e

To fix, just switch to https://github.com/Homebrew/brew/commit/9b76182c119abca16eaa3b1faa64bd08ca112be3

I have a very eventful day, unlikely to actually look into this issue. If someone has time, would appreciate the help.

**Comment by d12frosted** [comment]
Thanks to @juliocc , this should be fixed by now. Please do an update and try installing Emacs+ again.

**Comment by cilia** [comment]
Works again, thanks @d12frosted and @juliocc for a quick fix.
